"""update code_blocks for migration workflow

Revision ID: 094acd28c168
Revises: 48fb6d3c5c4d
Create Date: 2026-07-09 18:35:54.448217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '094acd28c168'
down_revision: Union[str, Sequence[str], None] = '48fb6d3c5c4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_blocks', sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False))
    op.alter_column('code_blocks', 'migrated_code',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('code_blocks', 'migrated_code',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('code_blocks', 'status')
    # ### end Alembic commands ###
