"""code-block change

Revision ID: 48fb6d3c5c4d
Revises: 079e103a84a2
Create Date: 2026-07-09 13:16:13.150260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48fb6d3c5c4d'
down_revision: Union[str, Sequence[str], None] = '079e103a84a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_blocks', sa.Column('original_code', sa.Text(), nullable=False))
    op.add_column('code_blocks', sa.Column('migrated_code', sa.Text(), nullable=False))
    op.drop_column('code_blocks', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_blocks', sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('code_blocks', 'migrated_code')
    op.drop_column('code_blocks', 'original_code')
    # ### end Alembic commands ###
