"""create zip_projects table

Revision ID: 7aa829f238bb
Revises: b18fffcf7447
Create Date: 2026-07-17 13:13:46.549836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aa829f238bb'
down_revision: Union[str, Sequence[str], None] = 'b18fffcf7447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zip_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('source_language', sa.String(length=50), nullable=True),
    sa.Column('target_language', sa.String(length=50), nullable=False),
    sa.Column('original_zip_path', sa.String(length=500), nullable=False),
    sa.Column('migrated_zip_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='UPLOADED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zip_projects_id'), 'zip_projects', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zip_projects_id'), table_name='zip_projects')
    op.drop_table('zip_projects')
    # ### end Alembic commands ###
